cohenlabUNC/clpipe

- clpipe/TestDocument.txt
Demonstrated pull requests to lab
> Created a demonstration document

- clpipe/config_json_parser.py
> Revert "Fixed issue with ROI extraction"

- clpipe/data/defaultConfig.json
- clpipe/fmri_postprocess2.py
- clpipe/postprocutils/workflows.py
- tests/test_postprocess2.py
Simple change of `ApplyAROMA` step to `AROMARegression`
Resolves #151
> Aroma Step Name Change

- clpipe/postprocutils/workflows.py
- tests/test_postprocess2.py
- tests/test_postprocess2_wfs.py
This PR adds an additional algorithm for temporal filtering that is based on fslmaths.
Includes tests for functionality of stand-alone workflow and integration with full postproc2 pipeline.
#155
Stand-alone workflow:
Integrated workflow:
> Temporal Filter fslmath Algorithm

- docs/postprocessing.rst
Minor correction to default value in fmri_process_check documentation.
> Correction in documentation

- clpipe/data/defaultConfig.json
- clpipe/fmri_postprocess2.py
- setup.py
- tests/conftest.py
- tests/data/dataset_description.json
- tests/test_postprocess2.py
> Use derivatives

- clpipe/data/defaultConfig.json
- clpipe/fmri_postprocess2.py
closes #175 
Handles multiple image spaces by letting the image space be specified in the config.
> Add config option to set image space.

- clpipe/fmri_postprocess2.py
- clpipe/postprocutils/workflows.py
Closes #177 
Confounds files now save properly with tsv delim and correct transposition.
Bug causing incorrect confound ordering fixed.
> Adjust counds output

- clpipe/fmri_postprocess2.py
- setup.py
Comment out the not-yet-ready nilearn plotting, which has a matpotlib dependency.
> Remove nilearn Dependency

- setup.py
CLI entrypoint for postproc2 was pointing to the wrong place.
> Fix the fmri_postproc2 entrypoint.

- clpipe/data/defaultConfig.json
- setup.py
AROMA regression and temporal filtering to their working
variants.
> Change the default postproc2 implementations for

- clpipe/fmri_preprocess.py
- setup.py
Fix a bug that did not allow --use-aroma flag to be added to fmriprep command through the config file UseAROMA option.
> 1.6.0.2 hotfix

- clpipe/project_setup.py
- clpipe/utils.py
- setup.py
Added code to change user permissions of clpipe.log
> Log permissions

- clpipe/cli.py
- clpipe/fmri_process_check.py
- clpipe/utils.py
- tests/conftest.py
- tests/test_fmri_process_check.py
- tests/utils.py
Changes:
- Using new config for fmri-process-check
- Updated fmri-process-check to work with v21/v22
- Added fmri-process-check to clpipe cli
- Changed logging system
- Wrote tests for fmri-process-check
> Fmri process check

- clpipe/cli.py
- clpipe/data/defaultConfig.json
- clpipe/fmri_postprocess.py
- clpipe/utils.py
- setup.py
- tests/cli/test_glm.py
- tests/conftest.py
- tests/test_fmri_postprocess.py
- tests/test_glm_launch.py
Fixes an import issue with "legacy-style" glm_launch commands. Also adds some tests for launch commands.
> 1.7.3.3 hotfix

- clpipe/data/defaultConfig.json
- clpipe/fmri_postprocess.py
- clpipe/utils.py
- setup.py
- tests/conftest.py
- tests/test_fmri_postprocess.py
This change updates the logging of the original postprocessing command to use clpipe's new logging system.
Currently does not print any log messages due to its use of the generic logger.
Also adds some tests for the original postprocessing command.
> 1.7.3.2 hotfix

- clpipe/config/package.py
- clpipe/config_json_parser.py
- clpipe/data/defaultConfig.json
- clpipe/errors.py
- clpipe/fsl_onset_extract.py
- clpipe/postprocutils/confounds_workflows.py
- clpipe/project_setup.py
- clpipe/roi_extractor.py
- tests/conftest.py
- tests/postprocess2/test_confounds_workflows.py
- tests/postprocess2/test_workflow_chains.py
- tests/test_roi_extractor.py
- tests/utils.py
In addition to the previous 2 hotfixes, updates ROI extract command to work with newer version of fMRIPrep, the new logging system, and adds some new log messages.
closes #376 
closes #377 
closes #378
> 1.8.0.5 hotfix

- clpipe/config/package.py
- clpipe/fsl_onset_extract.py
- clpipe/postprocutils/confounds_workflows.py
- tests/postprocess2/test_confounds_workflows.py
- tests/postprocess2/test_workflow_chains.py
Fixes some logging related issues with fsl onset extract and corrects an old reference to "Algoirthms" in confounds wf
> 1.8.0.4 hotfix

- clpipe/config/package.py
- clpipe/roi_extractor.py
Fixes an issue with the order of logic in ROI extract introduced by 1.8.0.5. Adds some more log messages.
> 1.8.0.6 hotfix

- .lmod/module_file_template.txt
- clpipe/batchConfigs/slurmUNCConfig.json
- clpipe/bids_validator.py
- clpipe/cli.py
- clpipe/config/options.py
- clpipe/config/package.py
- clpipe/postprocutils/confounds_workflows.py
- clpipe/roi_extractor.py
- tests/test_roi_extractor.py
Fixes some issues with ROI extract interfaces with new config.
@trh3 merging this one should merge the last two patches as well
> 1.9.0.8 hotfix

- clpipe/batchConfigs/slurmUNCConfig.json
- clpipe/bids_validator.py
- clpipe/config/package.py
- clpipe/postprocutils/confounds_workflows.py
Fixes an issue with import paths when running confound workflows.
> 1.9.0.6 hotfix

- clpipe/batchConfigs/slurmUNCConfig.json
- clpipe/bids_validator.py
- clpipe/cli.py
- clpipe/config/options.py
- clpipe/config/package.py
- clpipe/postprocutils/confounds_workflows.py
- clpipe/roi_extractor.py
Fixes some small bugs with the ROI extract command.
Also removes some too-strict validations in the config file.
closes #426
> 1.9.0.7 hotfix
