cohenlabUNC/clpipe

clpipe/config_json_parser.py
Mask finder did not correctly find paths to brain masks when there are no sessions in a study.
=> Fixed issue with ROI extraction

.gitignore, requirements.txt
A few small adjustments to help with setting up dev environment.
Adding a `requirements.txt` lets a dev run `pip install -r requirements.txt` to get both the package's dependencies (`-e .` , 'editable' install of package, references `install_requires` list in setup.py) and libraries not necessary for package installation, but needed for dev environment (like pytest and wheel).
Ignore the whole `TestFiles` folder for reservation as a general sandbox space.
Additionally, ignore the `dist` build artifacts folder and some vscode IDE files.
=> Dev Environment Update

clpipe/data/defaultConfig.json, clpipe/postprocutils/workflows.py, tests/conftest.py, tests/test_postprocess2.py, tests/test_postprocess2_wfs.py
closes #152
Adds a resampling step option to the postprocessing workflow. This step uses the resample FLIRT node from glm_setup.py.
Adds new configuration options in the postproc2 section of clpipe_config.json
Adds tests for both the resample workflow in isolation and within a full workflow context.
Original Test Image:
Resampled Test Image:
Step in a full workflow context:
=> Add resample wf

clpipe/fmri_postprocess2.py, clpipe/postprocutils/workflows.py, tests/conftest.py, tests/test_postprocess2.py
Closes #159
Also addresses #165
Postproc2 now properly picks up on tasks with multiple runs:
The basic unit of processing job is now "SubjectImage," the combination of subject, task, and run, instead of "SubjectTaskJob," which did not account for multiple runs.
The job of finding images is moved up to the subject processing job, while identification of the TR is moved down to the SubjectImage job.
Additionally, try/catch logic is added to handling missing confounds/AROMA files.
=> Process by image

clpipe/data/R_scripts/fsl_regfilt.R, clpipe/fmri_postprocess2.py, clpipe/postprocutils/nodes.py, clpipe/postprocutils/r_setup.py, clpipe/postprocutils/workflows.py, clpipe/utils.py, setup.py
FSL's regfilt command won't work with the confounds-as-nifty pipeline, despite trying several attempts at changing the nii's format and digging into the regfilt code a bit.
This change adds in Dr. Hallquist's solution, which is an R script variant of fsl_regfilt.
Now, the confounds pipeline will always default to fsl_regfilt_R, a new workflow which calls a node that wraps this R script.
As a result of adding an R dependency, there are a few utility additions to support this.
=> Fsl regfilt r

clpipe/data/defaultConfig.json, clpipe/fmri_postprocess2.py
Addresses #171 
Simply adds a config option for working directory. Also changes the default working directory be in its own folder under the main postpro2 outputs folder, instead of appearing alongside each subject's output
=> Reroute working dirs

clpipe/bids_validator.py, clpipe/config_json_parser.py, clpipe/data/defaultConfig.json, clpipe/data/defaultConvConfig.json, clpipe/fmri_preprocess.py, setup.py
- Include TaskName sidecar change by default in dcm2bids template
- Automatically include a .bidsignore folder in bids folder, if not present
- Add a dedicated log folder for bids validation output
- UseAroma is now its own configuration option - no longer needs to be added as an extra option for fmriprep as "--use-aroma"
closes #204 
closes #196 
closes #195 
closes #148
=> Release 1.4.2

docs/bids_validation_tutorial.md, docs/conf.py, docs/dicom2bids_tutorial.md, docs/index.rst, docs/install_tutorial.md, docs/tutorial_index.md, requirements.txt
Provides a tutorial guiding a clpipe user from project setup through BIDS Validation using a publicly available dataset (the one used by dcm2bids)
=> Tutorial: Project Setup through BIDS Validation

README.md, docs/install.rst
git:// protocol was deprecated, updated install links to use https
=> Update install link to use https protocol.

docs/postprocessing.rst
Make sure temporal filtering and AROMAregression show the right default implementations.
=> Adjust default config documentation.

clpipe/fmri_postprocess.py, setup.py
Ensure the -TR flag is capitalized when distributing as expected by the cli. Ensure the tr is a float even if it comes from cli.
=> fmri_postprocess: Fix the -TR Flag

clpipe/cli.py, docs/bids_convert.rst, docs/bids_validation.rst, docs/fmriprep.rst, docs/glm.rst, docs/postprocessing.rst, docs/project_setup.rst, docs/roi_extraction.rst, setup.py
- Return accidentally removed "invoke_without_command" parameter to top cli function so that `clpipe -v` can be called
- Calling `clpipe status` without arguments now displays help info like the other commands instead of giving a missing input error
- Modify `glm launch` help description to match command name
- Update CLI documentation references to fix click command links broken by moving all CLI commands back to cli module
- Fix spelling of show atlases command name
=> 1.7.1.1 hotfix

.gitignore, clpipe/fmri_postprocess.py, clpipe/glm_setup.py, clpipe/postprocutils/utils.py, setup.py
Fixes import regression bugs in the original postprocessing command causing it to fail to run.
Basically just adjusting the imports from postproc utils. There is also a stray direct reference to python 3.6 that had to be removed due to us being on 3.7 now.
closes https://github.com/cohenlabUNC/clpipe/issues/285
=> 1.7.1.2 hotfix

docs/dicom_sync.rst
Short augmentation to the flywheel_sync documentation to add some detail about configuring a temporary directory, and describes how to set search depth options for dcm2bids.
=> Release 1.7.2

clpipe/utils.py
time format to shorten the line a bit.
We don't need millisecond time
resolution for this log file.
=> Remove milliseconds from the logger

clpipe/config.py, clpipe/fmri_postprocess2.py, setup.py
Fixes a race condition that causes postproc2 jobs to fail when they are creating directories for the first time.
Basically, its not smart to try to create the same file in multiple parallel jobs...
Also, fixes the default postproc2 stream, which I didn't notice was failing because I always tested with a specific stream.
=> 1.7.2.2 hotfix

clpipe/utils.py, setup.py
Fix an issue where getting the username fails when running clpipe from a node (often run into when using a desktop node)
closes #326
=> 1.7.3.1 hotfix

clpipe/cli.py, clpipe/config/package.py, clpipe/data/defaultConfig.json, clpipe/postprocutils/workflows.py, tests/conftest.py, tests/test_cli.py
Fixes an issue where the Confound Regression step was demeaning the timeseries data when using 3DTProject.
This update adds back the mean after 3DTProject runs.
Also fixes an issues where the default config file uses the algorithm "fsl_regfilt_R" for AROMA regression when it should be "fsl_regfilt," because the confound pipeline will use the R variant automatically.
closes #348
=> 1.8.0.2 hotfix

clpipe/cli.py, clpipe/config/package.py, tests/conftest.py, tests/test_cli.py
Fixes a leftover import in the CLI module which caused it to run slowly.
Also added a small test for top-level CLI and fixed a small issue with testing fixtures.
=> 1.8.0.1 hotfix

clpipe/job_manager.py
This PR hopes to finally resolve the issue with the threads not being passed in correctly. The last hotfix addressed the issue with the fmriprep preprocess function not getting the correct config arguments. But it turned out that issue also propagated further with those config arguments now not being passed in correctly to the batch manager.
This time, I did a more robust test by running the command on a test subject and ensuring the correct command is executed. I was able to verify on my end that the cpus-per-task are indeed set to the correct value based on the config file now. There was a couple of other issues I noticed as well, but I am making this PR out as soon as I can to get clpipe 1.9.1 back on track!
I would appreciate a speedy review @trh3! Cheers!
=> Resolve issue with threads not being passed correctly in job manager

.lmod/module_file_template.txt, .lmod/setup_modules.sh
r/4.2.1 is not required for clpipe purposes. On the Longleaf RHEL9 systems we have r/4.4.0 and r/4.5.0 which meet requirements in terms of versions.
=> fix r version issue
